import patrol from '../components/ennemies/patrol';
import { Trophies } from './trophies';

export const PLATFORMER_LEVELS = {
  [Trophies.LEMON]: [
    [
      '                          $',
      '                           ',
      '                          $',
      '                          $',
      '                          $',
      '           $$             $',
      '         ====             $',
      '     >                |   $',
      '                      |    ',
      '     > ^^      = >    |   @',
      '===========================',
    ],
    [
      '     $    $    $    $     $',
      '     $    $    $    $     $',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      ' @^^^>^^^^>^^^^>^^^^>^^^^^@',
      '===========================',
    ],
  ],
  [Trophies.ORANGE]: [
    [
      '                          $',
      '                           ',
      '                          $',
      '                          $',
      '                          $',
      '           $$             $',
      '         ====             $',
      '     >                =   $',
      '                      =    ',
      '     > ^^      = >    =   @',
      '===========================',
    ],
    [
      '     $    $    $    $     $',
      '     $    $    $    $     $',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      ' @^^^>^^^^>^^^^>^^^^>^^^^^@',
      '===========================',
    ],
  ],
  [Trophies.STRAWBERRY]: [
      [
        '               $$$$$$        ',
        '               ======        ',
        '                             ',
        '       @                     ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '        s                    ',
        '        =====              $ ',
        '                           $ ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '                             ',
        '     s    s   ^^   ^^>^^^^^@ ',
        '================ ≠ ========= ',
        '      $                     =',
        '      $                     2',
        '      $                      ',
        '      $                      ',
        '      $            s         ',
        '      $       ≠=====   $     ',
        '      =========        $     ',
        '                       $     ',
        '           $     $     $     ',
        '           $     $     $     ',
        '           $     $     $     ',
        '           $     $     $     ',
        ' | s    s  $   s $  |  $     ',
        ' ====================  $     ',
        '                             ',
        '                            e',
        '                            1',
        '                      ===   =',
        '                         ===='
      ],
    [
      '     $    $    $    $     $',
      '     $    $    $    $     $',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      ' @^^^>^^^^>^^^^>^^^^>^^^^^@',
      '===========================',
    ],
  ],
  [Trophies.CHERRY]: [
    [
      '                          $',
      '                           ',
      '                          $',
      '                          $',
      '                          $',
      '           $$             $',
      '         ====             $',
      '     >                =   $',
      '                      =    ',
      '     > ^^      = >    =   @',
      '===========================',
    ],
    [
      '     $    $    $    $     $',
      '     $    $    $    $     $',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      '                           ',
      ' @^^^>^^^^>^^^^>^^^^>^^^^^@',
      '===========================',
    ],
  ],
};

export const PLATFORMER_LEVEL_CONF = {
	// grid size
	width: 64,
	height: 64,
	// define each object as a list of components
	'=': () => [
    rect(64, 64),
    sprite('ground'),
		area(),
		solid(),
		// origin('bot'),
    'ground'
	],
	'^': () => [
		sprite('peaks'),
		area(),
		solid(),
		scale(4),
		// origin('bot'),
		'danger',
	],
  '|': () => [
    sprite('wall'),
    area(),
		// origin('bot'),
		scale(4),
    solid(),
		'wall',
  ],
	'>': () => [
		sprite('thrashMob1', { anim: 'active' }),
    area({ scale: 0.5 }),
		origin('bot'),
		scale(4),
		body(),
		patrol(),
		'enemy',
	],
	's': () => [
		sprite('strawberryMob'),
    area({ scale: 0.5 }),
		// origin('bot'),
		scale(4),
		body(),
		patrol(),
		'enemy',
	],
	'@': () => [
		sprite('gate'),
		area(),
		scale(4),
		// origin('bot'),
		pos(0, -12),
		'portal',
	],
  '1': () => [
    rect(64, 64),
    color(0, 255, 0),
		area(),
		solid(),
    'elevatorFrom',
  ],
  '2': () => [
    rect(64, 64),
    color(0, 255, 0),
		area(),
		solid(),
    'elevatorTo',
  ],
  'e': () => [
    rect(64, 64),
		area(),
		solid(),
		origin('bot'),
		body(),
    color(255, 0, 0),
    'elevator',
  ],
};
